config/routes.rb
Rails.application.routes.draw do
  
  resources :zoos
  # resources :donations
  # resources :wishes, except: [:new, :show]
  # resources :toys
  resources :keepers # path: :users (aliasing path causing issues with signing out)

  # resources :donors
  resources :animals, except: [:show]
  delete 'animals/:id', to: 'animals#destroy', as: :destroy_animal

  # get 'animals/:id/wishes/:wishes_id', to: 'wishes#show'
  post 'donations/search', to: 'donations#search', as: :donations_search
  
  # for wishes
  resources :wishes, only: [:index]
  get 'wishes/active', to: 'wishes#active'
  post 'wishes', to: 'wishes#create'

  # toys
  get 'toys', to: 'toys#index'

  # to reset donations for specific wish (used for JS frontend concept only)
  post 'wishes/:id/reset_donations', to: 'wishes#reset_donations'
  get 'wishes/reset_active_wishes', to: 'wishes#reset_active_wishes'

  resources :donations, only: [:index, :show, :create]
  
  # nested resources for new animal wish
  resources :animals, only: [:show] do
    resources :wishes, only: [:show] do # do wishes need to be nested in animals?
      resources :donations, only: [:new]
    end
  end

  # devise handles authentication
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  # to handle sign_in with custom controller actions:
  # devise_scope :user do
  #   post 'users/sign_in', to: 'sessions#create'
  # end
  devise_scope :user do
    get 'get_auth_token', to: 'sessions#get_token'
  end

  resources :users, only: [:show]

  root 'users#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donor.rb
class Donor < ApplicationRecord
    has_many :donations
    has_many :wishes, through: :donations
    has_many :toys, through: :wishes
    has_many :animals, through: :wishes
    belongs_to :user, optional: true
end

app/models/wish.rb
class Wish < ApplicationRecord
    # associations
    belongs_to :zoo, optional: true # only has zoo_id if zoo directly owns wish (instead of animal owning wish)
    belongs_to :animal
    belongs_to :toy
    has_many :donations
    has_many :donors, through: :donations
    
    # statuses: new, active, funded, ordered, shipped, delivered, fulfilled
    scope :unfunded, -> { where(status: 'new')}
    scope :active, -> { where(status: 'active')}
    scope :fulfilled, -> { where(status: 'fulfilled')}
    
    
    def keeper_id
        self.animal.keeper.id
    end

    def activate
        self.status = 'active'
        self.save
    end

    def self.reset_active_wishes
        Wish.active.each do |wish|
            wish.status = 'new'
            wish.save
        end
        Wish.all.sample(3).each do |wish|
            wish.activate
        end
    end

    def total_to_fund
        self.toy.cost
    end

    def current_funding
        self.donations.pluck(:amount).reduce(:+)
    end
    # TODO: freeze editing of certain attributes once status changes

end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController

    # display form for creating new wish, set animal for collection
    # route needs to be nested within animals resource
    
    # below commented out so authentication/authorization will not be needed for vanilla JS concept
    # before_action :authenticate_user!, except: [:index, :active, :reset_donations, :reset_active_wishes]
    # load_and_authorize_resource except: [:index, :active, :reset_donations, :reset_active_wishes]

    # for creating wishes using animal id and toy id
    def create
        animal = Animal.find_by(id: wish_params[:animal_id])
        wish = animal.wishes.new(toy_id: wish_params[:toy_id])
        if wish.valid?
            wish.save
            render json: wish, include: [:animal, :toy]
        else
            render json: wish.errors
        end
    end

    def new 
        # set animal 
        @animal = Animal.find_by(id: params[:animal_id])
    end

    def edit

    end

    def show
        @wish = Wish.find_by(id: params[:id])
    end

    def index
        
    end

    # display all wishes that are set to active
    def active
        wishes = Wish.active
        render json: wishes, include: [:animal, :toy]
    end

    # display all fulfilled wishes
    def fulfilled
        wishes = Wish.fulfilled
        render json: wishes, include: [:animal, :toy]
    end

    # below two methods for frontend js concept
    # DO NOT INCLUDE IN PRODUCTION
    def reset_donations
        wish = Wish.find_by(wish_params)
        wish.donations.each { |donation| donation.destroy }
        render json: wish, include: [:animal, :toy]
    end

    def reset_active_wishes
        Donation.destroy_all
        Wish.reset_active_wishes
        wishes = Wish.active
        render json: wishes, include: [:animal, :toy]
    end

    private

    def wish_params
        params.require(:wish).permit(:id, :animal_id, :toy_id) # actual attribute will be different once image uploading functionality is built
    end

end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/wishes/_active_index.html.erb
<h2>Donate to Wishes</h2>

<p>This section will contain a list of active wishes as cards. Wishes are set to active by 
controller and model logic (first they are selected at random to make it easy). Only a select 
number of wishes are active at any one time so donations are funnelled to be as effective as possible.</p>

<% Wish.active.each do |wish| %>
    <%= render partial: 'wishes/wish', locals: {wish: wish} %><br>
    <%= link_to "More Info", animal_path(wish.animal) %><br><br>
<% end %>

app/views/wishes/_collection_form.html.erb
<%= f.collection_check_boxes :toy_ids, Toy.all, :id, :id %><br>

app/views/wishes/_donor_index.html.erb
<h2>Wishes you have donated to:</h2>

<p>This section will contain a list of wishes you have donated to as cards.</p>

<% donor.wishes.each do |wish| %>
    <%= render partial: 'wishes/wish', locals: {wish: wish} %><br>
    <%= link_to "More Info", animal_path(wish.animal) %><br><br>
<% end %>

app/views/wishes/_fulfilled_index.html.erb
<h2>Fulfilled wishes</h2>

<p>Wish card will show the picture of the animal that was uploaded by the keeper when the toy was received (wishes are not marked as fulfilled until this image is uploaded). This section of fulfilled wishes will render for all visitors, regardless of being logged in or not.</p>

app/views/wishes/_keeper_index.html.erb
<h2>Wishes in your animals' wishlists:</h2>

<p>This section will contain a list of wishes in a keeper's wishlist. Will probably organize with sorting by using scopes.</p>

<% keeper.wishes.each do |wish| %>
    <%= render partial: 'wishes/wish', locals: {wish: wish} %><br>
    <%= link_to "More Info", animal_path(wish.animal) %><br><br>
<% end %>

app/views/wishes/_wish.html.erb
<b>Wish ID: </b><%= wish.id %><br>
<b>Animal: </b><%= wish.animal.name %><br>
<b>Toy: </b><%= wish.toy_id %>

<%= link_to "Donate", new_animal_wish_donation_path(wish.animal, wish) %>

app/views/wishes/index.html.erb
<h1>Wish Index</h1>

<p>This page will contain wishes displayed as cards.  
    Card will also have a link to the animal's profile page. Users can only see wishes that have been fulfilled or active (if they have donated to
    a wish, then by definition the wish is also either fulfilled or active.</p>

<!-- 
Render these partials into optional tabs
Or render a user nav bar with links to each
Use js to work with on front end
-->
<% if user_signed_in? %>
    <% if current_user.donor? %>
        <%= render partial: 'donor_index', locals: {donor: current_user.donor} %>
    <% end %>
    <% if current_user.keeper? %>
        <%= render partial: 'keeper_index', locals: {keeper: current_user.keeper} %>
    <% end %>
<% end %>

<%= render partial: 'active_index' %>

<%= render partial: 'fulfilled_index' %>

app/views/wishes/new.html.erb
<!-- 

display collection check boxes of toys
each item should have link to toy with more info

-->

<%= form_with model: @animal do |f| %>
    <label>Select toys for this animal's wishlist:</label>
    <%= render partial: 'collection_form', locals: {f: f} %><br>
    <%= f.submit "Edit Wishlist" %>
<% end %>

app/views/wishes/show.html.erb
<%= render partial: 'wish', locals: {wish: @wish} %>
<br>
<%= link_to "View Animal Profile", animal_path(@wish.animal) %>