config/routes.rb
Rails.application.routes.draw do
  
  resources :zoos
  # resources :donations
  # resources :wishes, except: [:new, :show]
  # resources :toys
  resources :keepers # path: :users (aliasing path causing issues with signing out)

  # resources :donors
  resources :animals, except: [:show]
  delete 'animals/:id', to: 'animals#destroy', as: :destroy_animal

  # get 'animals/:id/wishes/:wishes_id', to: 'wishes#show'
  post 'donations/search', to: 'donations#search', as: :donations_search
  
  # for wishes
  resources :wishes, only: [:index]
  get 'wishes/active', to: 'wishes#active'
  post 'wishes', to: 'wishes#create'

  # toys
  get 'toys', to: 'toys#index'

  # to reset donations for specific wish (used for JS frontend concept only)
  post 'wishes/:id/reset_donations', to: 'wishes#reset_donations'
  get 'wishes/reset_active_wishes', to: 'wishes#reset_active_wishes'

  resources :donations, only: [:index, :show, :create]
  
  # nested resources for new animal wish
  resources :animals, only: [:show] do
    resources :wishes, only: [:show] do # do wishes need to be nested in animals?
      resources :donations, only: [:new]
    end
  end

  # devise handles authentication
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  # to handle sign_in with custom controller actions:
  # devise_scope :user do
  #   post 'users/sign_in', to: 'sessions#create'
  # end
  devise_scope :user do
    get 'get_auth_token', to: 'sessions#get_token'
  end

  resources :users, only: [:show]

  root 'users#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donation.rb
class Donation < ApplicationRecord
    belongs_to :donor
    belongs_to :wish

    def donor_attributes=(donor_atts)
        # find donor by id in case user enters different email than what they have used previously
        # then use rest of provided info to update donor
        # currently, many donor models can have same email if they were created without also creating an account   
        self.donor = Donor.find_or_create_by(id: donor_atts[:id])
        self.donor.first_name = donor_atts[:first_name]
        self.donor.last_name = donor_atts[:last_name]
        self.donor.save
        # self.donor.update(donor_atts)
    end

    def animal_name
        self.wish.animal.name
    end

end

# donation = Donation.new(:wish_id => "8", :donor_attributes =>[:id => "4", :first_name=> "Bruce", :last_name => "Wayne", :email => "brucewayne@batcave.com"])

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
    load_and_authorize_resource only: [:index, :show]

    def search
        @animal = Animal.find_by(name: params[:name])
        @donations = @animal.donations
        render "index"
    end

    def show
    end

    def index
    end
   
    def new
        # use cancan to set?
        if user_signed_in? 
            donor = current_user.set_donor
        else
            donor = Donor.new
        end
        @donation = donor.donations.build(wish_id: params[:wish_id])

    end

    def create
        # create and save donation, if failed rerender form with errors
        
        # below method created before frontend build, use as reference for future methods
        # if user has account and is signed in, redirect to profile (change to donations index?)
        # if donation was made without creating account, redirect to home page
        # @donation = Donation.new(donation_params)
        # if @donation.save
        #     if user_signed_in?
        #         redirect_to donations_path 
        #     else
        #         redirect_to root_path
        #     end
        # else
        #     render "new"
        # end
       
        donation = Donation.new(donation_params)

        # if donation.amount + wish.current_funding > wish.total_to_fund
            # split donation and create new donation with amount overflow
            # apply that new donation the next wish that is activated
            # associate donor to both wishes


        if donation.valid?
            donation.save
        else
            puts "Error: #{donation.errors.full_messages}"
        end
        render json: donation
    end

    # /animals/5/wishes/8/donations/new

    private

    def donation_params
        params.require(:donation).permit(:wish_id, :amount, donor_attributes: [:id, :first_name, :last_name, :email])
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<h2>Donated to: </h2><%= donation.animal_name %>

app/views/donations/index.html.erb
<h1>Donation Index</h1>

<p>This page displays an index of donations that the logged in user is able to see.
    Zookeepers do not get a list of donations towards their animals.</p>

<% @donations.each do |donation| %>
    <%= render partial: 'donations/donation', locals: {donation: donation} %>
    <%= link_to "View Donation", donation_path(donation) %>
<% end %>

app/views/donations/new.html.erb
This will be a form to to create a new donation. Donations are associated with a wish.

Donations can be created by anyone, even visitors who do not have an account.

The form will include a checkbox for the option to create an account once the donation is complete.

<%= form_with model: @donation do |donation| %>
    <%# fields for Donor, either fill if user signed in or create one with form %>
    <%= donation.hidden_field :wish_id %>
    <%= donation.fields_for :donor_attributes, @donation.donor do |donor| %>
        <%= donor.hidden_field :id %>
        <%= donor.label "Your Name" %>
        <%= donor.text_field :first_name %> 
        <%= donor.text_field :last_name %>
        
        <%= donor.label :email %>
        <%= donor.email_field :email %>
    <% end %>
    <%= donation.submit %>
<% end %>

app/views/donations/show.html.erb
<h1>Main show page for individual donations</h1>



<h2>Donated to: </h2><%= @donation.animal_name %>

<h3>Render the wish with a link to view it.</h3>

<p>Will show options based on user type (what options needed?)</p>

<p>Show social share links.</p>