config/routes.rb
Rails.application.routes.draw do
  
  resources :zoos
  # resources :donations
  # resources :wishes, except: [:new, :show]
  # resources :toys
  resources :keepers # path: :users (aliasing path causing issues with signing out)

  # resources :donors
  resources :animals, except: [:show]
  delete 'animals/:id', to: 'animals#destroy', as: :destroy_animal

  # get 'animals/:id/wishes/:wishes_id', to: 'wishes#show'
  post 'donations/search', to: 'donations#search', as: :donations_search
  
  # for wishes
  resources :wishes, only: [:index]
  get 'wishes/active', to: 'wishes#active'
  post 'wishes', to: 'wishes#create'

  # toys
  get 'toys', to: 'toys#index'

  # to reset donations for specific wish (used for JS frontend concept only)
  post 'wishes/:id/reset_donations', to: 'wishes#reset_donations'
  get 'wishes/reset_active_wishes', to: 'wishes#reset_active_wishes'

  resources :donations, only: [:index, :show, :create]
  
  # nested resources for new animal wish
  resources :animals, only: [:show] do
    resources :wishes, only: [:show] do # do wishes need to be nested in animals?
      resources :donations, only: [:new]
    end
  end

  # devise handles authentication
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  # to handle sign_in with custom controller actions:
  # devise_scope :user do
  #   post 'users/sign_in', to: 'sessions#create'
  # end
  devise_scope :user do
    get 'get_auth_token', to: 'sessions#get_token'
  end

  resources :users, only: [:show]

  root 'users#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
    # associations
    belongs_to :keeper
    has_many :wishes, dependent: :delete_all # this needs to change so wishes other than 'new' status are archived
    has_many :toys, through: :wishes
    has_many :donations, through: :wishes
    has_many :donors, through: :donations

    # Active Storeage file associations
    has_many_attached :images

    # below method for frontend JS concept
    # TOO MANY DOTS!
    def location
        self.keeper.zoo.name + " - " + self.keeper.zoo.address.state + ", " + self.keeper.zoo.address.country
    end
    
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
    # add authentication and authorization checks before appropriate methods
    # use cancancan to set resources
    before_action :set_animal, only: [:show, :edit, :update, :destroy]
    # load_and_authorize_resource

    def index
        # animals = Animal.all

        # For react demo:
        animals = User.find_by(first_name: "Paul", last_name: "Blart").keeper.animals

        render json: animals
    end

    def new
        @animal = current_user.keeper.animals.build
    end

    def create
        # Get user from session params (current_user from Devise gem)
        # @animal = current_user.keeper.animals.build(animal_params)
        
        # Use demo keeper for developing react demo:
        @animal = User.find_by(first_name: "Paul", last_name: "Blart").keeper.animals.build(animal_params)

        # This line is really important
        if @animal.species == "Tiger" || @animal.species == "Lion"
            puts "Made a kitty =^.^="
        end

        if @animal.save
            render json: @animal
            # redirect_to animal_path(@animal)
        else
            render json: @animal.errors
            # render 'animals/new'
        end
    end

    def update 
        
        if @animal.update(animal_params)
            redirect_to animal_path(@animal)
        else
            render 'animals/edit'
        end
    end

    def destroy
        # For react demo:
        @animal = Animal.find_by(animal_params)
        
        @animal.destroy
        render json: @animal
    end

    private

    def set_animal
        @animal = Animal.find_by(id: params[:id])
    end

    def animal_params
        params.require(:animal).permit(:id, :name, :species, :bio, toy_ids: [], images: [])
    end

end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_animal.html.erb
<i>id: </i><%= animal.id %></i><br>
<b>Name: </b><%= animal.name %><br>
<b>Species: </b><%= animal.species %><br>
<b>Bio:</b><br>
<%= animal.bio %><br>
<b>Toys in wishlist:</b>
<%# render partial for toys %>
<% animal.wishes.each do |wish| %>
    <%= link_to "#{wish.toy_id}", animal_wish_path(animal, wish) %>
<% end %>

app/views/animals/_form.html.erb
<%# partial for creating and editing animal %>

<%= animal.label :name %>
<%= animal.text_field :name %><br>

<%= animal.label :species %>
<%= animal.text_field :species %><br>

<%= animal.label :bio %>
<%= animal.text_area :bio %><br>

app/views/animals/edit.html.erb
<h1>Edit Animal Profile</h1>

<%= form_with model: @animal do |animal| %>

    <%= render partial: 'form', locals: {animal: animal} %>

    <label>Select toys for this animal's wishlist:</label><br>
    <%= animal.collection_check_boxes :toy_ids, Toy.all, :id, :id %><br>

    <%= animal.submit %>

<% end %>

app/views/animals/index.html.erb
<% if current_user.keeper? %>
    <h2>Animals under your care:</h2>
    <% current_user.keeper_animals.each do |animal| %> 
        <%= render partial: 'animal', locals: {animal: animal} %><br>
        <%= link_to "More Info", animal_path(animal) %>
        <br><br>
    <% end %>
    <%= link_to "Add Animals", new_animal_path %>
<% end %>

<% if current_user.donor? && !current_user.donor_animals.empty? %>
    <h2>Animals you donated to:</h2>
    <% current_user.donor_animals.each do |animal| %> 
        <%= render partial: 'animal', locals: {animal: animal} %><br>
        <%= link_to "More Info", animal_path(animal) %>
        <br><br>
    <% end %>
<% else %>
    <h2>You haven't donated to any animals yet. Use controller to redirect?</h2>
<% end %>

<%= link_to "Back to Account", user_path(current_user) %>

<%# add admin index also %>
<%# refactor to partials %>

<h3>Search for an animal you donated to:</h3>
<%= form_tag donations_search_path do %>
    <%= text_field_tag :name %>
    <%= submit_tag "Search"%>
<% end %> 

app/views/animals/new.html.erb
<h1>New Animal Form</h1>

<%= form_with model: @animal do |animal| %>

    <%= render partial: 'form', locals: {animal: animal} %>

    <label>Select toys for this animal's wishlist:</label><br>
    <%= animal.collection_check_boxes :toy_ids, Toy.all, :id, :id %><br>

    <%= animal.submit %>

<% end %>

app/views/animals/show.html.erb
<h1>Animal Profile Page</h1>

<%= render partial: 'animal', locals: {animal: @animal} %>
<br>
<%= link_to "Edit Animal Profile", edit_animal_path %>
<br>
<%= link_to "Return to Index", animals_path %> 
<br>


<%= button_to "Delete", @animal, method: :delete, confirm: "Are you sure?" %>